name: UAT Distribution

on:
  push:
    branches:
      - main
      - release

jobs:
  build-and-distribute:
    runs-on: ubuntu-latest
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
      FASTLANE_USER: ${{ secrets.APPLE_ID }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      UAT_FEEDBACK_FORM: "https://forms.gle/your-google-form-link"

    steps:
      - uses: actions/checkout@v4

      # Install dependencies
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install npm dependencies
        run: npm install

      # Android build and Firebase App Distribution
      - name: Build Android APK
        run: |
          cd android
          ./gradlew assembleRelease

      - name: Distribute Android APK to Firebase App Distribution
        run: |
          npm install -g firebase-tools
          firebase appdistribution:distribute android/app/build/outputs/apk/release/app-release.apk \
            --app <FIREBASE_APP_ID> \
            --groups "uat-testers" \
            --token $FIREBASE_TOKEN \
            --release-notes "Automated UAT build. Please fill out the feedback form: $UAT_FEEDBACK_FORM"

      # iOS build and TestFlight (Fastlane)
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2

      - name: Install Fastlane
        run: gem install fastlane

      - name: Build and upload to TestFlight
        run: |
          cd ios
          fastlane beta

      # Notify testers (Slack)
      - name: Notify Slack
        uses: slackapi/slack-github-action@v1.25.0
        with:
          payload: |
            {
              "text": "🚀 New UAT build is available!\n\n*Android APK*: [Firebase App Distribution Link]\n*iOS*: Check TestFlight\n\nPlease fill out the feedback form: ${{ env.UAT_FEEDBACK_FORM }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
