apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      release: prometheus
  resources:
    requests:
      memory: 400Mi
  alerting:
    alertmanagers:
    - namespace: default
      name: alertmanager
      port: web
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
