apiVersion: v1
kind: Secret
metadata:
  name: beauty-crafter-secrets
type: Opaque
data:
  DATABASE_URL: <BASE64_ENCODED_DB_URL>
  STRIPE_SECRET_KEY: <BASE64_ENCODED_STRIPE_KEY>
  SESSION_SECRET: <BASE64_ENCODED_SESSION_SECRET>
  SNYK_TOKEN: <BASE64_ENCODED_SNYK_TOKEN>
  # Add other secrets as needed
